.github/workflows/maven.yml
push とプルリク時に Maven ビルドを走らせるワークフロー
=> [Add] GitHub Actions Workflow

plugin/src/main/java/net/okocraft/box/plugin/util/Colorizer.java
題通り。[TextLibs Colorizer](https://github.com/SiroPlugins/TextLibs/blob/master/src/main/java/com/github/siroshun09/textlibs/util/Colorizer.java) からのコピー (一部改変) である。
=> 1.16 の16進数カラーも変換可能な Colorizer

src/main/java/net/okocraft/box/command/box/DepositCommand.java, src/main/java/net/okocraft/box/command/box/ItemInfoCommand.java
existing items are treated as they do not exist.
=> Fix error that

src/main/java/net/okocraft/box/BoxAPI.java, src/main/java/net/okocraft/box/command/BaseCommand.java, src/main/java/net/okocraft/box/command/Commands.java, src/main/java/net/okocraft/box/config/CraftRecipes.java, src/main/java/net/okocraft/box/config/Messages.java, src/main/java/net/okocraft/box/gui/CraftGUI.java, src/main/java/net/okocraft/box/listeners/BoxStick.java, src/main/java/net/okocraft/box/listeners/PlayerListener.java, src/main/java/net/okocraft/box/listeners/Replant.java
=> Fixed and changed craft recipe feature.

bundle/src/main/resources/plugin.yml, features/craft/src/main/java/net/okocraft/box/feature/craft/button/CraftButton.java, features/craft/src/main/java/net/okocraft/box/feature/craft/command/CraftCommand.java, features/craft/src/main/java/net/okocraft/box/feature/craft/menu/RecipeItemIcon.java, features/craft/src/main/java/net/okocraft/box/feature/craft/util/IngredientRenderer.java, features/craft/src/main/java/net/okocraft/box/feature/craft/util/ItemCrafter.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/session/PlayerSession.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/command/MenuOpenCommand.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/mode/StorageMode.java
`/box gui {target}` で他のプレイヤーのデータで Box を開けるようにする。権限は `box.admin.command.gui.other`。
=> Other Player's GUI

bundle/build.gradle.kts, bundle/src/main/java/net/okocraft/box/bundle/Bundled.java, bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreMenuDisplays.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreSettingMenu.java, features/bemode/build.gradle.kts, features/bemode/src/main/java/net/okocraft/box/feature/bemode/BEModeFeature.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/lang/Displays.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/listener/MenuOpenListener.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/mode/AbstractStorageMode.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/mode/StorageDepositMode.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/mode/StorageWithdrawMode.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/util/BEPlayerChecker.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/mode/ClickModeRegistry.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/mode/StorageMode.java, settings.gradle.kts
related to #100 #101
GUI モジュールから切り離し、GUI モジュール側の変更を少なくすると主に、役割を明確化します
役割 - GUI モジュールは Java 版を前提とした実装、BEMode モジュールはそれを BE でも使いやすくする実装
=> Implements BE Mode

api/src/main/java/net/okocraft/box/api/message/Components.java, api/src/main/java/net/okocraft/box/api/message/GeneralMessage.java, core/src/main/java/net/okocraft/box/core/command/BoxAdminCommandImpl.java, core/src/main/java/net/okocraft/box/core/command/BoxCommandImpl.java, core/src/main/java/net/okocraft/box/core/message/ErrorMessages.java, core/src/main/java/net/okocraft/box/core/message/MicsMessages.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreMenuDisplays.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreSettingMenu.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/message/AutoStoreMessage.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/lang/Displays.java, features/category/src/main/java/net/okocraft/box/feature/category/CategoryFeature.java, features/command/src/main/java/net/okocraft/box/feature/command/message/BoxAdminMessage.java, features/command/src/main/java/net/okocraft/box/feature/command/message/BoxMessage.java, features/craft/src/main/java/net/okocraft/box/feature/craft/CraftFeature.java, features/craft/src/main/java/net/okocraft/box/feature/craft/lang/Displays.java, features/gui/src/main/java/net/okocraft/box/feature/gui/GuiFeature.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/command/MenuOpenCommand.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/lang/Displays.java, features/notifier/src/main/java/net/okocraft/box/feature/notifier/factory/NotificationFactory.java, features/stick/src/main/java/net/okocraft/box/feature/stick/command/CustomStickCommand.java, features/stick/src/main/java/net/okocraft/box/feature/stick/command/StickCommand.java
`Components` クラスを API に追加し、コンポーネント作成時のコード量を減らします。
実際の削減量はこのコミット (https://github.com/okocraft/Box/commit/14fb5f8dd7844e1f7751e87990f095bf173929bd ) で確認できます。
=> Reduce codes of creating components

api/src/main/java/net/okocraft/box/api/command/base/package-info.java, api/src/main/java/net/okocraft/box/api/command/package-info.java, api/src/main/java/net/okocraft/box/api/event/feature/package-info.java, api/src/main/java/net/okocraft/box/api/event/general/package-info.java, api/src/main/java/net/okocraft/box/api/event/item/package-info.java, api/src/main/java/net/okocraft/box/api/event/package-info.java, api/src/main/java/net/okocraft/box/api/event/player/package-info.java, api/src/main/java/net/okocraft/box/api/event/stock/package-info.java, api/src/main/java/net/okocraft/box/api/event/stockholder/package-info.java, api/src/main/java/net/okocraft/box/api/feature/package-info.java, api/src/main/java/net/okocraft/box/api/message/argument/package-info.java, api/src/main/java/net/okocraft/box/api/message/package-info.java, api/src/main/java/net/okocraft/box/api/model/data/package-info.java, api/src/main/java/net/okocraft/box/api/model/item/package-info.java, api/src/main/java/net/okocraft/box/api/model/manager/package-info.java, api/src/main/java/net/okocraft/box/api/model/stock/package-info.java, api/src/main/java/net/okocraft/box/api/model/user/package-info.java, api/src/main/java/net/okocraft/box/api/package-info.java, api/src/main/java/net/okocraft/box/api/player/package-info.java, api/src/main/java/net/okocraft/box/api/taskfactory/package-info.java, api/src/main/java/net/okocraft/box/api/transaction/package-info.java, api/src/main/java/net/okocraft/box/api/util/package-info.java
=> Add package-info to api module

api/src/main/java/net/okocraft/box/api/BoxAPI.java, api/src/main/java/net/okocraft/box/api/feature/AbstractBoxFeature.java, api/src/main/java/net/okocraft/box/api/feature/BoxFeature.java, build-logic/src/main/kotlin/box.dependencies.gradle.kts, build-logic/src/main/kotlin/box.publication.gradle.kts, core/src/main/java/net/okocraft/box/core/BoxPlugin.java, core/src/main/java/net/okocraft/box/core/listener/DebugListener.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/listener/AutoSaveListener.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/listener/BoxPlayerListener.java, features/bemode/src/main/java/net/okocraft/box/feature/bemode/BEModeFeature.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/CustomItemListener.java, features/notifier/src/main/java/net/okocraft/box/feature/notifier/listener/StockHolderListener.java
=> [v5] Update Event4J

bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreMenuDisplays.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreSettingMenu.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/listener/ItemListener.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/message/AutoStoreMessage.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/model/AutoStoreSettingSerializer.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/model/setting/AutoStoreSetting.java
Added direct auto-store feature, which stores items from block drop.
=> feat: implemented direct auto-store

bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreAllCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreCommandUtil.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreDirectCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreItemCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreSubCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/message/AutoStoreMessage.java
Divided AutoStoreCommand into some files.
AutoStoreCommand lines: 260 -> 100 (instead, added 5 files)
=> Refactor Auto-store module - divide AutoStoreCommand class.

bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreAllCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreCommandUtil.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreDirectCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreItemCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/command/AutoStoreSubCommand.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreMenuDisplays.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/AutoStoreSettingMenu.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/buttons/AbstractAutoStoreSettingButton.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/buttons/BulkEditingButton.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/buttons/DirectButton.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/buttons/ModeButton.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/gui/buttons/ToggleButton.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/message/AutoStoreMessage.java, features/autostore/src/main/java/net/okocraft/box/feature/autostore/model/setting/AutoStoreSetting.java
=> Refactor Auto-store Module

bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, bundle/src/main/resources/plugin.yml, features/command/src/main/java/net/okocraft/box/feature/command/CommandFeature.java, features/command/src/main/java/net/okocraft/box/feature/command/boxadmin/ResetAllCommand.java, features/command/src/main/java/net/okocraft/box/feature/command/message/BoxAdminMessage.java
=> Rename reset command to reset all

features/stick/src/main/java/net/okocraft/box/feature/stick/integration/LWCIntegration.java, gradle/libs.versions.toml
NOTE: SUPPLY is the protection type that is only available in OKOCRAFT currently.
=> Support the new protection type of LWC: SUPPLY

api/src/main/java/net/okocraft/box/api/util/MCDataVersion.java, core/src/main/java/net/okocraft/box/core/BoxPlugin.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/categorizer/ExperimentalItems.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/file/BundledCategoryFile.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/file/CategoryLoader.java, gradle/libs.versions.toml, storage/database/src/main/java/net/okocraft/box/storage/implementation/database/table/ItemTable.java
=> Minecraft 1.19.4

api/src/main/java/net/okocraft/box/api/event/player/PlayerCollectItemInfoEvent.java, bundle/src/main/resources/en.yml, bundle/src/main/resources/ja_JP.yml, features/category/src/main/java/net/okocraft/box/feature/category/CategoryFeature.java, features/category/src/main/java/net/okocraft/box/feature/category/api/category/Category.java, features/category/src/main/java/net/okocraft/box/feature/category/api/category/CategoryImpl.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/listener/ItemInfoEventListener.java, features/command/src/main/java/net/okocraft/box/feature/command/box/ItemInfoCommand.java
- `PlayerCollectItemInfoEvent`
- `Category#containsItem`
=> Improve Item Info

features/craft/src/main/java/net/okocraft/box/feature/craft/util/ItemCrafter.java
=> fix(craft): increase stock of ingredient's "crafting remaining item"

api/src/main/java/net/okocraft/box/api/transaction/InventoryTransaction.java, features/stick/build.gradle.kts, features/stick/src/main/java/net/okocraft/box/feature/stick/function/container/ChestAccessChecker.java, features/stick/src/main/java/net/okocraft/box/feature/stick/integration/BoltIntegration.java, features/stick/src/main/java/net/okocraft/box/feature/stick/integration/LWCIntegration.java, features/stick/src/main/java/net/okocraft/box/feature/stick/integration/ProtectionPluginIntegration.java, gradle/libs.versions.toml
Added integration for [Bolt](https://github.com/pop4959/Bolt).
This PR is **NOT** tested yet.
=> Add Bolt Integration

features/category/src/main/java/net/okocraft/box/feature/category/internal/listener/ItemInfoEventListener.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/menu/paginate/AbstractPaginatedMenu.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/menu/paginate/PaginatedMenu.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/util/MenuOpener.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/command/MenuOpenCommand.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/holder/BoxInventoryHolder.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/listener/InventoryListener.java, features/gui/src/main/java/net/okocraft/box/feature/gui/internal/menu/CategoryMenu.java
https://github.com/okocraft/Box/assets/39247022/ea51d471-bead-4adc-bba0-08e90ab87ce9
=> Open CategoryMenu on clicking the item in player's inventory

.github/workflows/deployment.yml, .github/workflows/gradle.yml, README.md, build-logic/src/main/kotlin/box.common-conventions.gradle.kts, features/category/src/main/java/net/okocraft/box/feature/category/internal/category/LoadedCategory.java, features/category/src/main/java/net/okocraft/box/feature/category/internal/file/CategoryFile.java, features/command/src/main/java/net/okocraft/box/feature/command/boxadmin/RegisterCommand.java, features/command/src/main/java/net/okocraft/box/feature/command/boxadmin/RenameCommand.java, features/craft/src/main/java/net/okocraft/box/feature/craft/command/CraftCommand.java, features/craft/src/main/java/net/okocraft/box/feature/craft/gui/button/IngredientButton.java, features/craft/src/main/java/net/okocraft/box/feature/craft/gui/util/IngredientRenderer.java, features/craft/src/main/java/net/okocraft/box/feature/craft/mode/CraftMode.java, features/gui/src/main/java/net/okocraft/box/feature/gui/api/session/PlayerSession.java, gradle/libs.versions.toml, versions/paper-1_21/src/main/java/net/okocraft/box/version/paper_1_21/Paper_1_21.java
This PR updates the version of Java used in this project to 21. With this, the Java runtime version required by Box will also be 21.
**Do not merge until the following is resolved**:
=> Update to Java 21
